modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0 license"

[[mods]]
modId="falling_waterfalls"
version="1.0.0"
logoFile="falling_falls.png"
displayName="Falling Waterfalls"
displayURL="https://github.com/PotionSeeker/Falling-Waterfalls"
authors="PotionSeeker"
description='''
Prevents players from swimming up waterfalls, with a new potion effect to bypass this restriction.
'''

[[dependencies.falling_waterfalls]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.falling_waterfalls]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"