modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0 license"
issueTrackerURL="https://github.com/yourusername/fallingwaterfalls/issues"

[[mods]]
modId="falling_waterfalls"
version="1.0.0"
logoFile="falling_falls.png"
displayName="Falling Waterfalls"
displayURL="https://github.com/PotionSeeker/Falling-Waterfalls"
authors="PotionSeeker"
description='''
A mod that prevents players from swimming up waterfalls, unless they follow the art of the salmon.
'''

[[dependencies.falling_waterfalls]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21]"
ordering="NONE"
side="BOTH"

[[dependencies.falling_waterfalls]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"