modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0 license "

[[mods]]
modId="falling_waterfalls"
version="1.0.0"
logoFile = "falling_falls.png"
displayName="Falling Waterfalls"
displayURL="https://github.com/PotionSeeker/Falling-Waterfalls"
authors="PotionSeeker"
description='''
Prevents players from swimming up waterfalls, and a new potion effect to prevent this.
'''

[[dependencies.falling_waterfalls]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"
